stages:
  - test

.install-dependencies:
  image: mambaorg/micromamba:bookworm-slim
  before_script:
    - micromamba install --yes --name base --file environment.yml
    - micromamba clean --all --yes
    - micromamba run poetry config virtualenvs.create false --local
    - micromamba run poetry install
    - export PYTHONPATH="$PYTHONPATH:src"

unit-tests:
  stage: test
  extends: .install-dependencies
  script:
    - micromamba run python tests/tests_runner.py

docstring-tests:
  stage: test
  extends: .install-dependencies
  script:
    - micromamba run python tests/doctests_runner.py
