version: 1

formatters:
  simple:
    format: '%(message)s'
  detailed:
    format: '%(asctime)s %(filename)s:%(lineno)d - %(levelname)s - %(message)s'
    datefmt: '[%Y-%m-%d %H:%M:%S]'

handlers:
  console:
    class: rich.logging.RichHandler
    formatter: simple
  file:
    class: logging.handlers.RotatingFileHandler
    formatter: detailed
    filename: fstg_toolkit.log
    maxBytes: 1_048_576
    backupCount: 3

root:
  level: NOTSET
  handlers: [console, file]